class Solution {
    public:
        int maxDiff(int num) {
                string str1 = to_string(num); // for max value
                        string str2 = str1;           // for min value
                                int n = str1.size();

                                        // Maximize: Change first non-9 digit to 9
                                                char ele1 = 0;
                                                        for (int i = 0; i < n; i++) {
                                                                    if (str1[i] != '9') {
                                                                                    ele1 = str1[i];
                                                                                                    break;
                                                                                                                }
                                                                                                                        }
                                                                                                                                if (ele1 != 0) {
                                                                                                                                            for (int i = 0; i < n; i++) {
                                                                                                                                                            if (str1[i] == ele1) str1[i] = '9';
                                                                                                                                                                        }
                                                                                                                                                                                }

                                                                                                                                                                                        // Minimize: Change first digit to '1' or others to '0'
                                                                                                                                                                                                char ele2 = 0, replace = 0;
                                                                                                                                                                                                        if (str2[0] != '1') {
                                                                                                                                                                                                                    ele2 = str2[0];
                                                                                                                                                                                                                                replace = '1';
                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                    for (int i = 1; i < n; i++) {
                                                                                                                                                                                                                                                                    if (str2[i] != '0' && str2[i] != '1') {
                                                                                                                                                                                                                                                                                        ele2 = str2[i];
                                                                                                                                                                                                                                                                                                            replace = '0';
                                                                                                                                                                                                                                                                                                                                break;
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                            if (ele2 != 0) {
                                                                                                                                                                                                                                                                                                                                                                                        for (int i = 0; i < n; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                        if (str2[i] == ele2) str2[i] = replace;
                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                    return stoi(str1) - stoi(str2);
                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                        };